# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0002_season_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='seriesRus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=200)),
                ('duration', models.CharField(default='30:25', max_length=50)),
                ('season', models.IntegerField()),
                ('number', models.IntegerField()),
                ('description', models.CharField(default='description', max_length=1000)),
                ('SEOtext', models.CharField(default='SEO', max_length=800)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='seriesEng',
            fields=[
                ('seriesrus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mirror.seriesRus')),
                ('subtitlesRus', models.CharField(default='in static folder', max_length=200)),
                ('subtitlesEng', models.CharField(default='in static folder', max_length=200)),
            ],
            bases=('mirror.seriesrus',),
        ),
    ]
