# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0003_serieseng_seriesrus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serieseng',
            name='seriesrus_ptr',
        ),
        migrations.RemoveField(
            model_name='seriesrus',
            name='SEOtext',
        ),
        migrations.RemoveField(
            model_name='seriesrus',
            name='image',
        ),
        migrations.AddField(
            model_name='seriesrus',
            name='video',
            field=models.CharField(default='static/', max_length=500),
        ),
        migrations.AlterField(
            model_name='seriesrus',
            name='description',
            field=models.TextField(default='description', max_length=1000),
        ),
        migrations.DeleteModel(
            name='seriesEng',
        ),
    ]
