# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0005_seriesrus_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='seriesEng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(default='static/', max_length=500)),
                ('subtitlesRus', models.ImageField(blank=True, upload_to='documents/subtitlesRus')),
                ('subtitlesEng', models.ImageField(blank=True, upload_to='documents/subtitlesEng')),
                ('description', models.TextField(default='description', max_length=1000)),
                ('obj', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mirror.seriesRus')),
            ],
        ),
    ]
