# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0006_serieseng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serieseng',
            name='description',
            field=models.TextField(blank=True, default='description', max_length=1000),
        ),
    ]
