# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0007_auto_20170118_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesrus',
            name='obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mirror.season'),
        ),
    ]
