# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0008_seriesrus_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='description',
            field=models.TextField(default='some text', max_length=500),
        ),
    ]
