# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0014_auto_20170118_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesrus',
            name='image',
            field=models.ImageField(blank=True, upload_to='mirror/static/mirror/img/holder/'),
        ),
    ]
